[project]
name = "superego-lgdemo"
version = "0.1.0"
description = "Superego Chat System with LangGraph"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]

dependencies = [
    "typer",
    "colorama",
    "rich",
    "langchain-core",
    "langchain-anthropic",
    "langgraph",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
# uv-specific configuration
python = "3.9+"

# Entry points for CLI tools
[project.scripts]
superego = "cli:app"
