declare global {
    interface UISessionState {
        sessionId: string;
        name: string;
        createdAt: string;
        lastUpdatedAt: string;
        threads: Record<string, ThreadConfigState>; // Key is frontend-generated threadId (UUID)
    }

    /** Represents the configuration state for a single thread/config card in the UI */
    interface ThreadConfigState {
        // threadId (the key in UISessionState.threads) is generated by frontend (UUID)
        name: string; // User-editable name (e.g., "Default", "Strict Rules")
        runConfig: RunConfig; // The specific config for THIS thread
        isEnabled: boolean; // Should new messages be sent to this thread?
    }

    // Represents a configured constitution module, used both internally and for API payload.
    // Must have title, level, and EITHER id (remote lookup key) OR full text (local).
    type ConfiguredConstitutionModule = {
        title: string;
        adherence_level: number;
    } & ({ relativePath: string; text?: never } | { text: string; relativePath?: never });

    interface RunConfig {
        configuredModules: ConfiguredConstitutionModule[];
    }

    interface CheckpointConfigurable {
        thread_id: string | null;
        runConfig: RunConfig;
    }

    interface HistoryEntry {
        checkpoint_id: string;
        thread_id: string;
        values: {
            messages: MessageType[];
        };
        runConfig: RunConfig;
    }

    /** Possible statuses for a thread in the UI cache */
    type ThreadStatus = 'idle' | 'fetchingHistory' | 'streaming' | 'error';


    /** Wrapper object stored in the thread cache */
    interface ThreadCacheData {
        history: HistoryEntry | null;
        status: ThreadStatus;
        error: string | null;
    }

    // --- Hierarchical Constitution Types ---

    interface BaseConstitutionMetadata {
        title: string;
        description?: string;
        source: 'local' | 'remote';
    }

    interface LocalConstitutionMetadata extends BaseConstitutionMetadata {
        source: 'local';
        localStorageKey: string; // Unique key for localStorage
        text: string;
    }

    interface RemoteConstitutionMetadata extends BaseConstitutionMetadata {
        source: 'remote';
        relativePath: string; // Unique identifier from backend (e.g., "folder/file.md")
        filename: string;
    }

    interface ConstitutionFolder {
        folderTitle: string;
        relativePath: string;
        constitutions: RemoteConstitutionMetadata[];
        subFolders: ConstitutionFolder[];
    }

    interface ConstitutionHierarchy {
        rootConstitutions: RemoteConstitutionMetadata[];
        rootFolders: ConstitutionFolder[];
    }

    // --- UI Tree Node Types ---

    interface UINodeBase {
        type: 'folder' | 'file';
        uiPath: string; // Unique path for UI state (e.g., "local/key", "remote/rel/path")
    }

    interface UIFolderNode extends UINodeBase {
        type: 'folder';
        title: string;
        children: UINode[];
        isExpanded: boolean; // State for UI expansion
    }

    interface UIFileNode extends UINodeBase {
        type: 'file';
        metadata: LocalConstitutionMetadata | RemoteConstitutionMetadata;
    }

    type UINode = UIFolderNode | UIFileNode;


    interface BaseApiMessage {
        type: 'human' | 'ai' | 'system' | 'tool';
        content: string | any;
        name?: string;
        tool_call_id?: string;
        additional_kwargs?: Record<string, any>;
        nodeId: string;
    }

    interface HumanApiMessage extends BaseApiMessage {
        type: 'human';
        content: string;
    }

    interface AiApiMessage extends BaseApiMessage {
        type: 'ai';
        content: string | any;
        tool_calls?: Array<{ id: string; name: string; args: string; }>;
        invalid_tool_calls?: any[];
    }

    interface SystemApiMessage extends BaseApiMessage {
        type: 'system';
        content: string;
    }

    interface ToolApiMessage extends BaseApiMessage {
        type: 'tool';
        content: string | any;
        tool_call_id: string;
        name?: string;
        is_error?: boolean;
    }

    /** Represents message types received from the backend API. */
    type MessageType = HumanApiMessage | AiApiMessage | SystemApiMessage | ToolApiMessage;


    /** Input structure for starting a run */
    interface StreamRunInput {
        type: "human";
        content: string;
    }


    // --- Server-Sent Event (SSE) Data Types ---

    /** Structure for text chunks */
    interface SSEChunkData {
        node: string;
        content: string;
    }

    /** Structure for tool call fragments streamed from the AI */
    interface SSEToolCallChunkData {
        node: string;
        id?: string | null;
        name?: string | null;
        args?: string | null;
    }

    /** Structure for completed tool results */
    interface SSEToolResultData {
        node: string;
        tool_name: string;
        content: string;
        is_error: boolean;
        tool_call_id?: string | null;
    }

    /** Structure for error events */
    interface SSEErrorData {
        node: string;
        error: string;
    }

    /** Structure for the final 'end' event payload */
    interface SSEEndData {
        node: string;
        thread_id: string;
        checkpoint_id?: string | null;
    }

    /** Structure for the initial 'run_start' event payload */
    interface SSERunStartData {
        node: string;
        thread_id: string;
        runConfig: RunConfig;
        initialMessages: MessageType[];
    }

    /** Overall structure of data received via SSE */
    interface SSEEventData {
        type: "run_start" | "chunk" | "ai_tool_chunk" | "tool_result" | "error" | "end";
        thread_id?: string | null;
        data: SSERunStartData | SSEChunkData | SSEToolCallChunkData | SSEToolResultData | SSEErrorData | SSEEndData | any;
    }

    // --- Other API Types ---
    /** Request body for submitting a new constitution */
    interface ConstitutionSubmission {
        text: string;
        is_private: boolean;
    }

    /** Response from submitting a new constitution */
    interface SubmissionResponse {
        status: string;
        message: string;
        email_sent: boolean;
    }



}

export { };
